---
version: 2

defaults: &defaults
  docker:
    - image: circleci/ruby:2.5.1-node-browsers-legacy
  working_directory: ~/circleci-gcp-agent
  environment:
    LIBRARY: joatmon08
    CONTAINER_NAME: circleci-gcp-agent
    VERSION: 1.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the runner
          command: |
            docker build -t $LIBRARY/$CONTAINER_NAME:latest .
            docker tag $LIBRARY/$CONTAINER_NAME:latest $LIBRARY/$CONTAINER_NAME:$VERSION.$CIRCLE_BUILD_NUM
      - run:
          name: Push the image to Docker Hub
          command: |
            echo $DOCKER_HUB_KEY | docker login -u $DOCKER_HUB_USER --password-stdin
            docker push $LIBRARY/$CONTAINER_NAME:$VERSION.$CIRCLE_BUILD_NUM
  test:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dependencies
          command: bundle install
      - run:
          name: configuration tests
          command: |
            echo $DOCKER_HUB_KEY | docker login -u $DOCKER_HUB_USER --password-stdin
            docker pull $LIBRARY/$CONTAINER_NAME:$VERSION.$CIRCLE_BUILD_NUM
            CID="$(docker run -d -v /var/run/docker.sock:/var/run/docker.sock:ro $LIBRARY/$CONTAINER_NAME:$IMAGE_VERSION sleep 360)"
            inspec exec profiles/circleci_gcp_agent -t docker://$CID
            docker rm -f $CID

workflows:
  version: 2
  circleci-gcp-agent:
    jobs:
      - build
      - test:
          requires:
            - build